name: movie_sansaar_mobile
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0

  # Cupertino-style icons for iOS
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5

  # Network requests
  http: ^1.4.0

  # Persistent local storage
  shared_preferences: ^2.5.3

  # YouTube & video players
  youtube_player_flutter: ^9.1.1
  video_player: ^2.10.0
  better_player: ^0.0.84
  chewie: ^1.12.1

  # UI Enhancements
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.3.1

  # Browser and URL launchers
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0

  # Voice Recognition
  speech_to_text: ^7.1.0
  permission_handler: ^12.0.0+1

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11

  # Date & time formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/ms_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/ms_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF" # or "#000000" for dark splash
  image: assets/logo/ms_logo.png
  branding: assets/logo/ms_logo.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
